# Generated by Django 2.2.10 on 2020-05-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_article',
            field=models.CharField(default=999, max_length=300),
            preserve_default=False,
        ),
    ]
