# Generated by Django 2.2.10 on 2020-05-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0004_post_text_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_article',
            field=models.TextField(),
        ),
    ]
