# Generated by Django 2.2.10 on 2020-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0008_comment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='slug',
        ),
    ]
