# Generated by Django 2.2.10 on 2020-05-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=999, max_length=200),
            preserve_default=False,
        ),
    ]
