# Generated by Django 2.2.10 on 2020-05-07 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0012_category_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='category_url',
        ),
    ]
